// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpUXwL7tHozBDhFE_ETbqyHxKq2JOjlgY',
    appId: '1:949319381417:web:261e006d9c7d528211d4b8',
    messagingSenderId: '949319381417',
    projectId: 'ui-project-48c2a',
    authDomain: 'ui-project-48c2a.firebaseapp.com',
    storageBucket: 'ui-project-48c2a.appspot.com',
    measurementId: 'G-SRKF9L73SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6kNuWPAg2OuVcG49Ajg1Xlt129xjM7FE',
    appId: '1:949319381417:android:0a3cead15ff3b75211d4b8',
    messagingSenderId: '949319381417',
    projectId: 'ui-project-48c2a',
    storageBucket: 'ui-project-48c2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlGarIg512FrdUMcRzXlDtbAuFKib6UQo',
    appId: '1:949319381417:ios:5414291016bcd3a111d4b8',
    messagingSenderId: '949319381417',
    projectId: 'ui-project-48c2a',
    storageBucket: 'ui-project-48c2a.appspot.com',
    iosBundleId: 'com.example.uiUniversidadesGp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlGarIg512FrdUMcRzXlDtbAuFKib6UQo',
    appId: '1:949319381417:ios:5414291016bcd3a111d4b8',
    messagingSenderId: '949319381417',
    projectId: 'ui-project-48c2a',
    storageBucket: 'ui-project-48c2a.appspot.com',
    iosBundleId: 'com.example.uiUniversidadesGp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpUXwL7tHozBDhFE_ETbqyHxKq2JOjlgY',
    appId: '1:949319381417:web:c9f0f509d973426811d4b8',
    messagingSenderId: '949319381417',
    projectId: 'ui-project-48c2a',
    authDomain: 'ui-project-48c2a.firebaseapp.com',
    storageBucket: 'ui-project-48c2a.appspot.com',
    measurementId: 'G-5YDZ5RMSBB',
  );
}
